### ISSUE TITLE
AEM logs tracking

### ISSUE THREAD

**Issue by pun-ky** [Cognifide/cogboard#55]
it would be nice if feature of  https://github.com/Cognifide/gradle-aem-plugin#task-instancetail
 / standalone tailer https://github.com/Cognifide/gradle-aem-plugin/tree/master/dists/gradle-aem-tailer will be reflected in CogBoard

I am convinced that implementation could be done purely in JS

features to reflect:

- parsing AEM endpoint which outputs log entries (keep in mind that this endpoint could respond same log entries, so that JS parsing based on timestamp is needed to avoid analyzing duplicates)
- incident reporting when cannonade of unknown errors occurred (after deploying CRX package with defect to be able to inform user who performed deploy about his mistake)
- filtering errors / to avoid reporting errors already known (not problematic,mitigated)
- threshold of error count in case of time - colour of card on the board could  be red if e.g limit of more than 10 errors per minute will be exceeded

**Comment by szymon-owczarzak** [comment]
Thanks @pun-ky, this is valid case for AEM instances. I will describe this feature more from widget POV.

### AC:
- [ ] Admin can choose **Endpoint** for AEM instance
- [ ] Admin can set **Schedule Period**
- [ ] Admin can choose/type-in **File Name** for log source - default: error.log
- [ ] Admin can choose **Log Level** - default WARN
- [ ] Admin can set **Number of Presented Logs** - default 20 ?
- [ ] User can see logs in a widget
- [ ] User can easily see Log Level - example WARN - yellow | ERROR - red
- [ ] Widget is updated only when new logs that meet given criteria are present
