### ISSUE TITLE
Widget | Todo List

### ISSUE THREAD

**Issue by GrzegorzBednarski** [Cognifide/cogboard#83]
I want to have kind of project checklist.

**AC**
- [x] Admin can set title
- [x] Admin can add/edit/remove checklist items
- [x] Admin can clear resolved items (button, then confirmation popup)
- [x] User can see checklist 
- [x] User can mark items on list as resolved / unresolved by clicking checkbox
- [x] Item marked as a resolved will put at the bottom of list (should be styled as striked out)
- [x] Item unmarked from resolved to unresolved should back to its previous position (according to ordering)
- [x] ToDo list status should be saved automatically (without clicking save button)
- [x] Automated tests provided
